### ISSUE TITLE
Can't assume role in other account

### ISSUE THREAD

**Issue by MaoChhaya** [wata727/packer-plugin-amazon-ami-management#194]
I am using Packer `1.7.2` to build AMI in OU account by using **assume_role** but I can't use this plugin to manage AMIs in that account.

Does this plugin support **assume_role** block like packer?

**Comment by wata727** [comment]
As you say, this plugin does not support assuming roles now.
As with Packer, we can support it by taking `assume_role` into account when building an access config.
https://github.com/wata727/packer-plugin-amazon-ami-management/blob/ecba5958e32827a7e7aaddd935f010e69010c9b9/access_config.go

**Comment by MaoChhaya** [comment]
### Tuition Fee and Payment

All majors of study of Bachelor’s Degree Programs offered at CamTech charge the same fee. The tuition fee payment is made by the academic terms (three terms per academic year) as below:

|No.|Faculties|Tuition Fee |||Tuition fee/year|Total Tuition Fee (4 years)|30% off/year|30% off/term|
|   |   |Term I|Term II|Term III|   |   |   |   |
|:-:|:-:|:----:|:-----:|:------:|:-:|:-:|:-:|:-:|
| 1 |Engineering|1334$|1334$|1334$|4000$|16000$|2800$|934$|
| 2 |Built Environment|1334$|1334$|1334$|4000$|16000$|2800$|934$|
| 3 |Applied Science|1334$|1334$|1334$|4000$|16000$|2800$|934$|
| 4 |Arts, Humanities and Social Science|1167$|1167$|1167$|3500$|14000$|2450$|817$|
| 5 |Business and Management|1167$|1167$|1167$|3500$|14000$|2450$|817$|
