### ISSUE TITLE
Compatibility packer 1.10

### ISSUE THREAD

**Issue by DeLoWaN** [wata727/packer-plugin-amazon-ami-management#407]
Hi !

It's [me](https://github.com/wata727/packer-plugin-amazon-ami-management/issues/163) again.

Packer 1.10 break this plugin with this error (it is working fine with 1.9.5):

```
Error: Unknown data type amazon-ami
  on gitlab-runner.pkr.hcl line 36:
  (source code not available)
known data sources: [http null hcp-packer-image hcp-packer-iteration]
Error: Unknown source type amazon-ebs
  on gitlab-runner.pkr.hcl line 92:
  (source code not available)
The source amazon-ebs is unknown by Packer, and is likely part of a plugin that
is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.
https://developer.hashicorp.com/packer/integrations?filter=amazon
Cleaning up project directory and file based variables
```

Thank you for your work !

**Comment by wata727** [comment]
Hmm, is this error related to this plugin?
It appears that the removal of bundled plugins in Packer 1.10 is the cause.
https://www.hashicorp.com/blog/announcing-the-removal-of-bundled-plugins-in-hashicorp-packer

**Comment by DeLoWaN** [comment]
Ah, you're right. I wrongly assumed that amazon-ami comes from this plugin. Adding amazon plugin manually fixed the issue.
