### ISSUE TITLE
Getting Failed getting the "github.com/wata727/amazon-ami-management" plugin error 

### ISSUE THREAD

**Issue by tarvez05** [wata727/packer-plugin-amazon-ami-management#408]
I am using github.com/wata727/amazon-ami-management plugin in my github action pipeline to manage packer AMIs,
i have started getting below error

Run packer init aws-ms_windows.pkr.hcl
Failed getting the "github.com/wata727/amazon-ami-management" plugin:
1 error occurred:
	* binary reported a pre-release version of 1.4.1-dev
Remote installation of pre-release plugin versions is unsupported.
This is likely an upstream issue, which should be reported.

![image](https://github.com/wata727/packer-plugin-amazon-ami-management/assets/117841357/8edd57c5-6e85-4226-a2a5-9a5e2d070b39)

**Comment by wata727** [comment]
Thank you for reporting this. This is fixed in v1.5.0.
