### ISSUE TITLE
Improvement when call to ec2 DescribeLaunchTemplateVersions use ResolveAlias parameter to get the AMI ID.

### ISSUE THREAD

**Issue by jorovipe97** [wata727/packer-plugin-amazon-ami-management#430]
Hi, I'm using this plugin to delete old AMIs. However I found the following case:

When I create a LaunchTemplate that uses [AWS Systems Manager parameters instead of AMI IDs in launch templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html). The `Cleaner::setLaunchTemplateUsed()` does not detect the actual AMI ID as used.

Because we [do not pass](https://github.com/wata727/packer-plugin-amazon-ami-management/blob/2924897de989882f09476f845ad305695dae5ac7/cleaner.go#L214C30-L214C60) the `ResolveAlias` parameter to the `DescribeLaunchTemplateVersions` API call.

My proposal is to pass the paremter as follows:

```go
versions, err := c.ec2conn.DescribeLaunchTemplateVersions(&ec2.DescribeLaunchTemplateVersionsInput{
        LaunchTemplateId: lt.LaunchTemplateId,
        ResolveAlias: true // TODO: Get this from packer template configuration.
})
```

If you like the proposal. I would like to contribute to the repo by creating a Pull Request with this change. I just need a link to the contributions guidelines or any advise you can give me.

Thanks in advance. And thanks for making this plugin, which is super useful.

### A little background about me in case you find it useful

I am a full-stack engineer with 6 years of experience, I'm 3x AWS Certified (DevOps Profesional, Developer Associate, Solution Architect Associate). Here is my [linkedin page](https://www.linkedin.com/in/jose-romualdo-v-636b45a4/) with a more detailed CV.

**Comment by wata727** [comment]
This proposal makes sense. PRs are welcome.

**Comment by jorovipe97** [comment]
Nice, I will prepare a PR and let you know when is ready.

**Comment by jorovipe97** [comment]
Hi @wata727 Just to let you know that I opened this PR with the discussed proposal. https://github.com/wata727/packer-plugin-amazon-ami-management/pull/431.

I needed to update the initial approach due to a limitation on the `DescribeLaunchTemplateVersions` API. I left details in the PR description.
